# Generated by Django 6.0.3 on 2026-03-22 11:56

import apps.data_warehouse.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0001_initial'),
        ('etl_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la mesure')),
                ('column', models.CharField(max_length=200, verbose_name='Colonne source')),
                ('aggregation_type', models.CharField(choices=[('sum', '➕ Somme'), ('avg', '📊 Moyenne'), ('count', '🔢 Comptage'), ('min', '⬇️ Minimum'), ('max', '⬆️ Maximum'), ('count_distinct', '🎯 Comptage distinct'), ('stddev', '📉 Écart-type'), ('variance', '📊 Variance')], max_length=20, verbose_name="Type d'agrégation")),
                ('alias', models.CharField(blank=True, max_length=200, verbose_name='Alias')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Mesure calculée')),
                ('formula', models.TextField(blank=True, help_text='Pour les mesures calculées', verbose_name='Formule')),
                ('format_string', models.CharField(blank=True, max_length=50, verbose_name='Format')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Décimales')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'db_table': 'data_warehouse_measures',
                'ordering': ['fact_table', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataWarehouseSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom du schéma')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_tablespace', models.CharField(blank=True, max_length=100, verbose_name='Tablespace par défaut')),
                ('default_compression', models.BooleanField(default=True, verbose_name='Compression par défaut')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('table_count', models.IntegerField(default=0, verbose_name='Nombre de tables')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Taille totale (octets)')),
                ('last_analyzed', models.DateTimeField(blank=True, null=True, verbose_name='Dernière analyse')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dw_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Schéma Data Warehouse',
                'verbose_name_plural': 'Schémas Data Warehouse',
                'db_table': 'data_warehouse_schemas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataWarehouseTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom de la table')),
                ('table_type', models.CharField(choices=[('fact', '📊 Table des faits'), ('dimension', '📐 Table de dimension'), ('aggregate', '📈 Table agrégée'), ('bridge', '🌉 Table de pont'), ('staging', '📥 Table de staging')], db_index=True, max_length=20, verbose_name='Type de table')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', '✅ Actif'), ('building', '🏗️ En construction'), ('deprecated', '⚠️ Obsolète'), ('archived', '📦 Archivé')], default='active', max_length=20, verbose_name='Statut')),
                ('dimension_type', models.CharField(blank=True, choices=[('conformed', '✅ Conforme'), ('degenerate', '📊 Dégénérée'), ('junk', '🗑️ Junk'), ('role_playing', '🎭 Rôle multiple'), ('slowly_changing', '🐢 Évolution lente (SCD)'), ('rapidly_changing', '⚡ Évolution rapide')], help_text='Pour les tables de dimension', max_length=20, null=True, verbose_name='Type de dimension')),
                ('scd_type', models.CharField(blank=True, choices=[('type0', '📝 Type 0 - Fixe'), ('type1', '🔄 Type 1 - Écrasement'), ('type2', '📅 Type 2 - Versionnage'), ('type3', "📊 Type 3 - Colonne d'historique"), ('type4', "📁 Type 4 - Table d'historique"), ('type6', '🔀 Type 6 - Hybride')], help_text='Pour les dimensions à évolution lente', max_length=10, null=True, verbose_name='Type SCD')),
                ('granularity', models.CharField(blank=True, choices=[('transaction', '📝 Transaction'), ('daily', '📅 Quotidienne'), ('weekly', '📆 Hebdomadaire'), ('monthly', '🗓️ Mensuelle'), ('quarterly', '📊 Trimestrielle'), ('yearly', '📈 Annuelle')], help_text='Pour les tables de faits', max_length=20, null=True, verbose_name='Granularité')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='Colonnes')),
                ('primary_key', models.JSONField(blank=True, default=list, verbose_name='Clé primaire')),
                ('foreign_keys', models.JSONField(blank=True, default=list, verbose_name='Clés étrangères')),
                ('indexes', models.JSONField(blank=True, default=list, verbose_name='Index')),
                ('is_partitioned', models.BooleanField(default=False, verbose_name='Partitionné')),
                ('partition_column', models.CharField(blank=True, max_length=200, verbose_name='Colonne de partition')),
                ('partition_type', models.CharField(blank=True, choices=[('range', '📊 Range'), ('list', '📋 List'), ('hash', '#️⃣ Hash')], max_length=20, verbose_name='Type de partition')),
                ('partition_expression', models.TextField(blank=True, validators=[apps.data_warehouse.validators.validate_partition_expression], verbose_name='Expression de partition')),
                ('partition_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de partitions')),
                ('is_compressed', models.BooleanField(default=False, verbose_name='Compressé')),
                ('tablespace', models.CharField(blank=True, max_length=100, verbose_name='Tablespace')),
                ('row_count', models.BigIntegerField(default=0, verbose_name='Nombre de lignes')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('refresh_frequency', models.CharField(choices=[('realtime', '⚡ Temps réel'), ('hourly', '🕓 Horaire'), ('daily', '📅 Quotidien'), ('weekly', '📆 Hebdomadaire'), ('monthly', '🗓️ Mensuel'), ('manual', '👤 Manuel')], default='daily', max_length=20, verbose_name='Fréquence de rafraîchissement')),
                ('last_refresh', models.DateTimeField(blank=True, null=True, verbose_name='Dernier rafraîchissement')),
                ('next_refresh', models.DateTimeField(blank=True, null=True, verbose_name='Prochain rafraîchissement')),
                ('refresh_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Durée rafraîchissement (ms)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('business_owner', models.CharField(blank=True, max_length=200, verbose_name='Propriétaire métier')),
                ('documentation_url', models.URLField(blank=True, verbose_name='URL documentation')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='data_warehouse.datawarehouseschema', verbose_name='Schéma')),
                ('source_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_tables', to='etl_engine.etlpipeline', verbose_name='Pipeline ETL source')),
                ('source_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_tables', to='data_sources.datatable', verbose_name='Table source')),
                ('technical_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dw_tables', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire technique')),
            ],
            options={
                'verbose_name': 'Table Data Warehouse',
                'verbose_name_plural': 'Tables Data Warehouse',
                'db_table': 'data_warehouse_tables',
                'ordering': ['schema', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataWarehouseMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('query_time_ms', models.FloatField(blank=True, null=True, verbose_name='Temps de requête (ms)')),
                ('rows_scanned', models.BigIntegerField(blank=True, null=True, verbose_name='Lignes scannées')),
                ('bytes_read', models.BigIntegerField(blank=True, null=True, verbose_name='Octets lus')),
                ('cache_hit_ratio', models.FloatField(blank=True, null=True, verbose_name='Taux de cache')),
                ('table_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Taille table (octets)')),
                ('index_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Taille index (octets)')),
                ('partition_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de partitions')),
                ('compressed_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Taille compressée')),
                ('compression_ratio', models.FloatField(blank=True, null=True, verbose_name='Taux de compression')),
                ('custom_metrics', models.JSONField(blank=True, default=dict, verbose_name='Métriques personnalisées')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='data_warehouse.datawarehousetable', verbose_name='Table concernée')),
            ],
            options={
                'verbose_name': 'Métrique Data Warehouse',
                'verbose_name_plural': 'Métriques Data Warehouse',
                'db_table': 'data_warehouse_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataWarehouseLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('refresh', '🔄 Rafraîchissement'), ('query', '📊 Requête'), ('optimize', '⚡ Optimisation'), ('analyze', '🔍 Analyse'), ('partition', '📁 Partitionnement')], max_length=20, verbose_name='Opération')),
                ('level', models.CharField(choices=[('info', 'ℹ️ Info'), ('warning', '⚠️ Warning'), ('error', '❌ Error'), ('debug', '🐛 Debug')], default='info', max_length=20, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='Durée (ms)')),
                ('rows_affected', models.BigIntegerField(blank=True, null=True, verbose_name='Lignes affectées')),
                ('query', models.TextField(blank=True, verbose_name='Requête SQL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack trace')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_warehouse.datawarehousetable', verbose_name='Table concernée')),
            ],
            options={
                'verbose_name': 'Journal Data Warehouse',
                'verbose_name_plural': 'Journaux Data Warehouse',
                'db_table': 'data_warehouse_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregationTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('granularity', models.CharField(choices=[('transaction', '📝 Transaction'), ('daily', '📅 Quotidienne'), ('weekly', '📆 Hebdomadaire'), ('monthly', '🗓️ Mensuelle'), ('quarterly', '📊 Trimestrielle'), ('yearly', '📈 Annuelle')], max_length=20, verbose_name='Granularité')),
                ('group_by_columns', models.JSONField(default=list, verbose_name='Colonnes de groupement')),
                ('aggregated_columns', models.JSONField(default=dict, verbose_name='Colonnes agrégées')),
                ('refresh_frequency', models.CharField(choices=[('realtime', '⚡ Temps réel'), ('hourly', '🕓 Horaire'), ('daily', '📅 Quotidien'), ('weekly', '📆 Hebdomadaire'), ('monthly', '🗓️ Mensuel'), ('manual', '👤 Manuel')], default='daily', max_length=20, verbose_name='Fréquence de rafraîchissement')),
                ('last_refresh', models.DateTimeField(blank=True, null=True, verbose_name='Dernier rafraîchissement')),
                ('row_count', models.BigIntegerField(default=0, verbose_name='Nombre de lignes')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('compression_ratio', models.FloatField(default=1.0, verbose_name='Taux de compression')),
                ('base_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='data_warehouse.datawarehousetable', verbose_name='Table de base')),
            ],
            options={
                'verbose_name': "Table d'agrégation",
                'verbose_name_plural': "Tables d'agrégation",
                'db_table': 'data_warehouse_aggregations',
                'ordering': ['base_table', 'granularity'],
            },
        ),
        migrations.CreateModel(
            name='DimensionTable',
            fields=[
            ],
            options={
                'verbose_name': 'Table de dimension',
                'verbose_name_plural': 'Tables de dimension',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_warehouse.datawarehousetable',),
        ),
        migrations.CreateModel(
            name='FactTable',
            fields=[
            ],
            options={
                'verbose_name': 'Table des faits',
                'verbose_name_plural': 'Tables des faits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data_warehouse.datawarehousetable',),
        ),
        migrations.CreateModel(
            name='DimensionAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'attribut")),
                ('column', models.CharField(max_length=200, verbose_name='Colonne source')),
                ('data_type', models.CharField(choices=[('integer', '🔢 Entier'), ('bigint', '📊 Grand entier'), ('decimal', '💵 Décimal'), ('float', '📈 Float'), ('date', '📅 Date'), ('datetime', '⏰ Date/heure'), ('timestamp', '🕐 Timestamp'), ('boolean', '✅ Booléen'), ('varchar', '📝 Texte'), ('text', '📄 Texte long'), ('json', '🔧 JSON'), ('uuid', '🆔 UUID')], max_length=20, verbose_name='Type de données')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_key', models.BooleanField(default=False, verbose_name='Clé de dimension')),
                ('is_hierarchical', models.BooleanField(default=False, verbose_name='Hiérarchique')),
                ('format_string', models.CharField(blank=True, max_length=50, verbose_name='Format')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_warehouse.dimensionattribute', verbose_name='Attribut parent')),
            ],
            options={
                'verbose_name': 'Attribut de dimension',
                'verbose_name_plural': 'Attributs de dimension',
                'db_table': 'data_warehouse_dimension_attributes',
                'ordering': ['dimension_table', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StarSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fact_columns', models.JSONField(blank=True, default=list, verbose_name='Colonnes des faits')),
                ('dimension_columns', models.JSONField(blank=True, default=dict, verbose_name='Colonnes des dimensions')),
                ('relationships', models.JSONField(blank=True, default=dict, verbose_name='Relations')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('query_count', models.IntegerField(default=0, verbose_name='Nombre de requêtes')),
                ('last_queried_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière requête')),
                ('avg_query_time_ms', models.FloatField(default=0, verbose_name='Temps moyen de requête (ms)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_star_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Schéma en étoile',
                'verbose_name_plural': 'Schémas en étoile',
                'db_table': 'data_warehouse_star_schemas',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='datawarehouseschema',
            index=models.Index(fields=['name'], name='data_wareho_name_5bb455_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehouseschema',
            index=models.Index(fields=['is_active'], name='data_wareho_is_acti_84b4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehouseschema',
            index=models.Index(fields=['owner'], name='data_wareho_owner_i_a1b480_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehousetable',
            index=models.Index(fields=['schema', 'name'], name='data_wareho_schema__c5fb48_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehousetable',
            index=models.Index(fields=['table_type'], name='data_wareho_table_t_958f44_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehousetable',
            index=models.Index(fields=['status'], name='data_wareho_status_a40694_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehousetable',
            index=models.Index(fields=['-last_refresh'], name='data_wareho_last_re_932050_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datawarehousetable',
            unique_together={('schema', 'name')},
        ),
        migrations.AddIndex(
            model_name='datawarehousemetric',
            index=models.Index(fields=['table', '-timestamp'], name='data_wareho_table_i_1d579d_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehouselog',
            index=models.Index(fields=['table', '-created_at'], name='data_wareho_table_i_575054_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehouselog',
            index=models.Index(fields=['operation'], name='data_wareho_operati_37b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='datawarehouselog',
            index=models.Index(fields=['level'], name='data_wareho_level_b97f08_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationtable',
            index=models.Index(fields=['base_table', 'granularity'], name='data_wareho_base_ta_fd57ea_idx'),
        ),
        migrations.AddField(
            model_name='starschema',
            name='dimension_tables',
            field=models.ManyToManyField(related_name='star_schemas_dimension', to='data_warehouse.dimensiontable', verbose_name='Tables de dimensions'),
        ),
        migrations.AddField(
            model_name='dimensionattribute',
            name='dimension_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='data_warehouse.dimensiontable', verbose_name='Table de dimension'),
        ),
        migrations.AddField(
            model_name='starschema',
            name='fact_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_schemas_fact', to='data_warehouse.facttable', verbose_name='Table des faits'),
        ),
        migrations.AddField(
            model_name='measure',
            name='fact_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='data_warehouse.facttable', verbose_name='Table des faits'),
        ),
        migrations.AddIndex(
            model_name='dimensionattribute',
            index=models.Index(fields=['dimension_table', 'name'], name='data_wareho_dimensi_490b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionattribute',
            index=models.Index(fields=['is_key'], name='data_wareho_is_key_5bb6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionattribute',
            index=models.Index(fields=['is_active'], name='data_wareho_is_acti_f62330_idx'),
        ),
        migrations.AddIndex(
            model_name='starschema',
            index=models.Index(fields=['name'], name='data_wareho_name_1c0b94_idx'),
        ),
        migrations.AddIndex(
            model_name='starschema',
            index=models.Index(fields=['is_active'], name='data_wareho_is_acti_a404cf_idx'),
        ),
        migrations.AddIndex(
            model_name='starschema',
            index=models.Index(fields=['owner'], name='data_wareho_owner_i_38e2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='measure',
            index=models.Index(fields=['fact_table', 'name'], name='data_wareho_fact_ta_b0af39_idx'),
        ),
        migrations.AddIndex(
            model_name='measure',
            index=models.Index(fields=['is_active'], name='data_wareho_is_acti_1288d4_idx'),
        ),
    ]
