# Generated by Django 6.0.3 on 2026-03-22 18:42

import apps.notifications.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl_engine', '0001_initial'),
        ('visualizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('condition', models.CharField(choices=[('above', 'Au-dessus de'), ('below', 'En-dessous de'), ('equals', 'Égal à'), ('changed', 'Changement'), ('trend', 'Tendance'), ('percentage_change', 'Changement en pourcentage')], default='above', max_length=20, verbose_name='Condition')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='Seuil')),
                ('percentage_change', models.FloatField(blank=True, null=True, verbose_name='Changement en %')),
                ('check_frequency', models.CharField(choices=[('minute', 'Chaque minute'), ('hourly', 'Horaire'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='hourly', max_length=20, verbose_name='Fréquence')),
                ('cooldown_minutes', models.IntegerField(default=60, verbose_name='Cooldown (minutes)')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Dernier déclenchement')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='Nombre de déclenchements')),
                ('notification_channels', models.JSONField(blank=True, default=list, verbose_name='Canaux de notification')),
                ('notification_message', models.TextField(blank=True, verbose_name='Message personnalisé')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='visualizations.kpi', verbose_name='KPI')),
            ],
            options={
                'verbose_name': "Règle d'alerte",
                'verbose_name_plural': "Règles d'alerte",
                'db_table': 'alert_rules',
                'indexes': [models.Index(fields=['kpi', 'is_enabled'], name='alert_rules_kpi_id_84ff36_idx'), models.Index(fields=['condition'], name='alert_rules_conditi_189c1b_idx'), models.Index(fields=['last_triggered'], name='alert_rules_last_tr_af980f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('kpi_alert', '📊 Alerte KPI'), ('kpi_target_reached', '🎯 Objectif KPI atteint'), ('pipeline_complete', '✅ Pipeline ETL terminé'), ('pipeline_failed', '❌ Pipeline ETL échoué'), ('pipeline_started', '🚀 Pipeline ETL démarré'), ('report_ready', '📄 Rapport prêt'), ('dashboard_shared', '🔗 Dashboard partagé'), ('dashboard_exported', '📤 Dashboard exporté'), ('user_mention', '👤 Mention'), ('comment', '💬 Commentaire'), ('system_alert', '⚠️ Alerte système'), ('data_refresh', '🔄 Données rafraîchies'), ('anomaly_detected', '🔍 Anomalie détectée'), ('forecast_available', '📈 Prévision disponible'), ('user_welcome', '👋 Bienvenue'), ('password_reset', '🔐 Réinitialisation mot de passe'), ('email_verification', '✉️ Vérification email'), ('maintenance', '🔧 Maintenance planifiée'), ('weekly_digest', '📊 Digest hebdomadaire')], db_index=True, max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', '🟢 Basse'), ('medium', '🟡 Moyenne'), ('high', '🟠 Haute'), ('critical', '🔴 Critique')], default='medium', max_length=20, verbose_name='Priorité')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('queued', "📤 En file d'attente"), ('sent', '✅ Envoyé'), ('failed', '❌ Échoué'), ('delivered', '📬 Livré'), ('read', '📖 Lu'), ('archived', '📦 Archivé')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='Canaux')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='visualizations.dashboard')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='visualizations.kpi')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_items', to='etl_engine.etlpipeline', verbose_name='Pipeline ETL')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='visualizations.report')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'), models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', '📧 Email'), ('sms', '📱 SMS'), ('push', '📲 Push'), ('webhook', '🌐 Webhook'), ('slack', '💬 Slack'), ('teams', '💼 Microsoft Teams'), ('telegram', '✈️ Telegram'), ('whatsapp', '💚 WhatsApp')], db_index=True, max_length=20, verbose_name='Canal')),
                ('address', models.CharField(max_length=500, validators=[apps.notifications.validators.validate_email, apps.notifications.validators.validate_phone_number, apps.notifications.validators.validate_webhook_url], verbose_name='Adresse')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verification_token', models.CharField(blank=True, max_length=100, verbose_name='Token')),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Token envoyé le')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Dernier usage')),
                ('error_count', models.IntegerField(default=0, verbose_name="Nombre d'erreurs")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Canal de notification',
                'verbose_name_plural': 'Canaux de notification',
                'db_table': 'notification_channels',
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='notificatio_user_id_7ceccb_idx'), models.Index(fields=['channel', 'is_verified'], name='notificatio_channel_3d1d23_idx')],
                'unique_together': {('user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('kpi_alert', '📊 Alerte KPI'), ('kpi_target_reached', '🎯 Objectif KPI atteint'), ('pipeline_complete', '✅ Pipeline ETL terminé'), ('pipeline_failed', '❌ Pipeline ETL échoué'), ('pipeline_started', '🚀 Pipeline ETL démarré'), ('report_ready', '📄 Rapport prêt'), ('dashboard_shared', '🔗 Dashboard partagé'), ('dashboard_exported', '📤 Dashboard exporté'), ('user_mention', '👤 Mention'), ('comment', '💬 Commentaire'), ('system_alert', '⚠️ Alerte système'), ('data_refresh', '🔄 Données rafraîchies'), ('anomaly_detected', '🔍 Anomalie détectée'), ('forecast_available', '📈 Prévision disponible'), ('user_welcome', '👋 Bienvenue'), ('password_reset', '🔐 Réinitialisation mot de passe'), ('email_verification', '✉️ Vérification email'), ('maintenance', '🔧 Maintenance planifiée'), ('weekly_digest', '📊 Digest hebdomadaire')], db_index=True, max_length=50, verbose_name='Type de notification')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtres')),
                ('preferred_channels', models.JSONField(blank=True, default=list, verbose_name='Canaux préférés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='subscriptio_user_id_9f7a4d_idx'), models.Index(fields=['notification_type'], name='subscriptio_notific_de78f9_idx')],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
