# Generated by Django 6.0.3 on 2026-03-22 13:02

import apps.star_schema.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_warehouse', '0002_alter_measure_aggregation_type'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionalSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, validators=[apps.star_schema.validators.validate_schema_name], verbose_name='Nom du schéma')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('schema_type', models.CharField(choices=[('star', '⭐ Schéma en étoile'), ('snowflake', '❄️ Schéma en flocon'), ('galaxy', '🌌 Schéma galaxie'), ('constellation', '✨ Constellation de faits')], default='star', max_length=20, verbose_name='Type de schéma')),
                ('status', models.CharField(choices=[('draft', '📝 Brouillon'), ('active', '✅ Actif'), ('archived', '📦 Archivé'), ('deprecated', '⚠️ Obsolète')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('relationships', models.JSONField(blank=True, default=list, help_text='Définition des relations entre tables', validators=[apps.star_schema.validators.validate_relation_definition], verbose_name='Relations')),
                ('dimension_mapping', models.JSONField(blank=True, default=dict, help_text='Mapping des colonnes de dimensions', validators=[apps.star_schema.validators.validate_dimension_mapping], verbose_name='Mapping des dimensions')),
                ('measure_config', models.JSONField(blank=True, default=list, help_text='Configuration avancée des mesures (alias, format, etc.)', validators=[apps.star_schema.validators.validate_measure_definition], verbose_name='Configuration des mesures')),
                ('calculations', models.JSONField(blank=True, default=list, help_text='Formules de calcul personnalisées', verbose_name='Calculs personnalisés')),
                ('default_filters', models.JSONField(blank=True, default=list, help_text='Filtres appliqués par défaut', validators=[apps.star_schema.validators.validate_filter_expression], verbose_name='Filtres par défaut')),
                ('grain', models.CharField(choices=[('transaction', '📝 Transaction'), ('daily', '📅 Quotidien'), ('weekly', '📆 Hebdomadaire'), ('monthly', '🗓️ Mensuel'), ('quarterly', '📊 Trimestriel'), ('yearly', '📈 Annuel')], default='transaction', max_length=20, verbose_name='Grain')),
                ('default_join_type', models.CharField(choices=[('inner', '🔗 INNER JOIN'), ('left', '⬅️ LEFT JOIN'), ('right', '➡️ RIGHT JOIN'), ('full', '🔄 FULL OUTER JOIN'), ('cross', '✖️ CROSS JOIN')], default='left', max_length=20, verbose_name='Type de jointure par défaut')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('business_domain', models.CharField(blank=True, max_length=100, verbose_name='Domaine métier')),
                ('documentation_url', models.URLField(blank=True, verbose_name='URL documentation')),
                ('query_count', models.IntegerField(default=0, verbose_name='Nombre de requêtes')),
                ('last_queried_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière requête')),
                ('avg_query_time_ms', models.FloatField(default=0, verbose_name='Temps moyen de requête (ms)')),
                ('is_cached', models.BooleanField(default=False, verbose_name='Mise en cache')),
                ('cache_ttl_seconds', models.IntegerField(default=300, verbose_name='TTL cache (secondes)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dimensional_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('dimension_tables', models.ManyToManyField(blank=True, related_name='dimensional_schemas_as_dimension', to='data_warehouse.dimensiontable', verbose_name='Tables de dimensions')),
                ('fact_tables', models.ManyToManyField(related_name='dimensional_schemas_as_fact', to='data_warehouse.facttable', verbose_name='Tables de faits')),
                ('measures', models.ManyToManyField(blank=True, related_name='dimensional_schemas_as_measure', to='data_warehouse.measure', verbose_name='Mesures')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dimensional_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensional_schemas', to='users.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Schéma dimensionnel',
                'verbose_name_plural': 'Schémas dimensionnels',
                'db_table': 'dimensional_schemas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomCalculation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du calcul')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('calculation_type', models.CharField(choices=[('direct', '🎯 Direct'), ('aggregate', '📊 Agrégation'), ('ratio', '📐 Ratio'), ('trend', '📈 Tendance'), ('forecast', '🔮 Prédiction'), ('cumulative', '📊 Cumul'), ('moving_average', '📉 Moyenne mobile'), ('year_over_year', '📈 Variation annuelle'), ('month_over_month', '📊 Variation mensuelle'), ('percentage', '📊 Pourcentage')], default='direct', max_length=20, verbose_name='Type de calcul')),
                ('formula', models.TextField(help_text="Formule de calcul (ex: 'montant / quantite')", validators=[apps.star_schema.validators.validate_calculation_formula], verbose_name='Formule')),
                ('result_column', models.CharField(max_length=200, verbose_name='Colonne résultat')),
                ('result_type', models.CharField(default='decimal', max_length=50, verbose_name='Type du résultat')),
                ('format_string', models.CharField(blank=True, max_length=50, verbose_name="Format d'affichage")),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('decimal_places', models.IntegerField(default=2, verbose_name='Décimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('dimensional_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_calculations', to='star_schema.dimensionalschema', verbose_name='Schéma dimensionnel')),
            ],
            options={
                'verbose_name': 'Calcul personnalisé',
                'verbose_name_plural': 'Calculs personnalisés',
                'db_table': 'custom_calculations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimensionHierarchy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la hiérarchie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('levels', models.JSONField(default=list, help_text='Liste ordonnée des niveaux de hiérarchie', verbose_name='Niveaux')),
                ('default_level', models.CharField(blank=True, max_length=100, verbose_name='Niveau par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('rollup_enabled', models.BooleanField(default=True, verbose_name='Rollup activé')),
                ('drilldown_enabled', models.BooleanField(default=True, verbose_name='Drilldown activé')),
                ('dimension_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', to='data_warehouse.dimensiontable', verbose_name='Table de dimension')),
            ],
            options={
                'verbose_name': 'Hiérarchie de dimension',
                'verbose_name_plural': 'Hiérarchies de dimensions',
                'db_table': 'dimension_hierarchies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la relation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('from_column', models.CharField(max_length=200, verbose_name='Colonne source')),
                ('to_column', models.CharField(max_length=200, verbose_name='Colonne cible')),
                ('relation_type', models.CharField(choices=[('one_to_one', '1:1 - Un à un'), ('one_to_many', '1:N - Un à plusieurs'), ('many_to_one', 'N:1 - Plusieurs à un'), ('many_to_many', 'N:N - Plusieurs à plusieurs')], default='many_to_one', max_length=20, verbose_name='Type de relation')),
                ('join_type', models.CharField(choices=[('inner', '🔗 INNER JOIN'), ('left', '⬅️ LEFT JOIN'), ('right', '➡️ RIGHT JOIN'), ('full', '🔄 FULL OUTER JOIN'), ('cross', '✖️ CROSS JOIN')], default='left', max_length=20, verbose_name='Type de jointure')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activée')),
                ('cardinality', models.FloatField(default=1.0, verbose_name='Cardinalité estimée')),
                ('from_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='data_warehouse.facttable', verbose_name='Table de faits source')),
                ('to_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='data_warehouse.facttable', verbose_name='Table de faits cible')),
            ],
            options={
                'verbose_name': 'Relation entre faits',
                'verbose_name_plural': 'Relations entre faits',
                'db_table': 'fact_relationships',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalaxySchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la galaxie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('galaxy_relationships', models.JSONField(blank=True, default=list, verbose_name='Relations entre schémas')),
                ('schema_graph', models.JSONField(blank=True, default=dict, validators=[apps.star_schema.validators.validate_schema_graph], verbose_name='Graphe des schémas')),
                ('status', models.CharField(choices=[('draft', '📝 Brouillon'), ('active', '✅ Actif'), ('archived', '📦 Archivé'), ('deprecated', '⚠️ Obsolète')], default='draft', max_length=20, verbose_name='Statut')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('dimensional_schemas', models.ManyToManyField(related_name='galaxy_schemas', to='star_schema.dimensionalschema', verbose_name='Schémas dimensionnels')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galaxy_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Schéma galaxie',
                'verbose_name_plural': 'Schémas galaxie',
                'db_table': 'galaxy_schemas',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='dimensionalschema',
            index=models.Index(fields=['name'], name='dimensional_name_773589_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionalschema',
            index=models.Index(fields=['schema_type', 'status'], name='dimensional_schema__bdb904_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionalschema',
            index=models.Index(fields=['owner', 'team'], name='dimensional_owner_i_b8b347_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionalschema',
            index=models.Index(fields=['-query_count'], name='dimensional_query_c_4c1a32_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionalschema',
            index=models.Index(fields=['-created_at'], name='dimensional_created_898f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customcalculation',
            index=models.Index(fields=['name'], name='custom_calc_name_35b910_idx'),
        ),
        migrations.AddIndex(
            model_name='customcalculation',
            index=models.Index(fields=['dimensional_schema', 'is_active'], name='custom_calc_dimensi_aeb15d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customcalculation',
            unique_together={('dimensional_schema', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dimensionhierarchy',
            unique_together={('dimension_table', 'name')},
        ),
        migrations.AddIndex(
            model_name='factrelationship',
            index=models.Index(fields=['name'], name='fact_relati_name_83ef43_idx'),
        ),
        migrations.AddIndex(
            model_name='factrelationship',
            index=models.Index(fields=['from_fact', 'to_fact'], name='fact_relati_from_fa_3e8b38_idx'),
        ),
        migrations.AddIndex(
            model_name='factrelationship',
            index=models.Index(fields=['is_enabled'], name='fact_relati_is_enab_96cd68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factrelationship',
            unique_together={('from_fact', 'to_fact', 'from_column', 'to_column')},
        ),
        migrations.AddIndex(
            model_name='galaxyschema',
            index=models.Index(fields=['name'], name='galaxy_sche_name_6a94d1_idx'),
        ),
        migrations.AddIndex(
            model_name='galaxyschema',
            index=models.Index(fields=['status'], name='galaxy_sche_status_348000_idx'),
        ),
        migrations.AddIndex(
            model_name='galaxyschema',
            index=models.Index(fields=['owner'], name='galaxy_sche_owner_i_ef7128_idx'),
        ),
    ]
