# Generated by Django 6.0.3 on 2026-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='aggregation_type',
            field=models.CharField(choices=[('sum', '➕ Somme'), ('avg', '📊 Moyenne'), ('count', '🔢 Comptage'), ('min', '⬇️ Minimum'), ('max', '⬆️ Maximum'), ('count_distinct', '🔢 Comptage distinct'), ('median', '📈 Médiane'), ('std', '📉 Écart-type'), ('variance', '📊 Variance'), ('percentile_25', '📊 25ème percentile'), ('percentile_75', '📊 75ème percentile'), ('percentile_90', '📊 90ème percentile'), ('percentile_95', '📊 95ème percentile'), ('percentile_99', '📊 99ème percentile')], max_length=20, verbose_name="Type d'agrégation"),
        ),
    ]
