# Generated by Django 6.0.3 on 2026-03-21 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='Clé')),
                ('value', models.JSONField(default=dict, verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config_type', models.CharField(choices=[('general', '⚙️ Général'), ('security', '🛡️ Sécurité'), ('data_sources', '🗄️ Sources de données'), ('etl', '🔄 ETL'), ('warehouse', '🏢 Entrepôt'), ('visualization', '📊 Visualisation'), ('dashboard', '📈 Tableaux de bord'), ('kpi', '🎯 KPIs'), ('notifications', '🔔 Notifications'), ('exports', '📤 Exports'), ('integrations', '🔌 Intégrations')], default='general', max_length=20, verbose_name='Type')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Chiffré')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'core_config',
                'indexes': [models.Index(fields=['key'], name='core_config_key_2bfab5_idx'), models.Index(fields=['config_type'], name='core_config_config__93d50e_idx')],
            },
        ),
    ]
