# Generated by Django 6.0.3 on 2026-04-01 20:12

import apps.ml_analytics.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_warehouse', '0002_alter_measure_aggregation_type'),
        ('star_schema', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('model_type', models.CharField(choices=[('forecast', '📈 Prévision'), ('anomaly', "🔍 Détection d'anomalies"), ('segmentation', '👥 Segmentation'), ('recommendation', '💡 Recommandation'), ('classification', '🏷️ Classification'), ('regression', '📊 Régression'), ('clustering', '🔵 Clustering'), ('time_series', '⏱️ Série temporelle'), ('grok_insight', '🤖 Grok Insight')], db_index=True, max_length=20, verbose_name='Type de modèle')),
                ('algorithm', models.CharField(choices=[('prophet', 'Prophet (Facebook)'), ('arima', 'ARIMA'), ('sarima', 'SARIMA'), ('lstm', 'LSTM (Deep Learning)'), ('xgboost', 'XGBoost'), ('gradient_boosting', 'Gradient Boosting'), ('random_forest', 'Random Forest'), ('isolation_forest', 'Isolation Forest'), ('kmeans', 'K-Means'), ('dbscan', 'DBSCAN'), ('hierarchical', 'Hierarchical Clustering'), ('svm', 'SVM'), ('logistic_regression', 'Régression Logistique'), ('neural_network', 'Réseau de Neurones'), ('grok', '🤖 Grok AI (xAI)')], db_index=True, max_length=30, verbose_name='Algorithme')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('training', '🏋️ Entraînement'), ('trained', '✅ Entraîné'), ('failed', '❌ Échoué'), ('deployed', '🚀 Déployé'), ('deprecated', '⚠️ Obsolète'), ('archived', '📦 Archivé')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('config', models.JSONField(blank=True, default=dict, validators=[apps.ml_analytics.validators.validate_model_config], verbose_name='Configuration')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Features')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Précision (%)')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('rmse', models.FloatField(blank=True, null=True, verbose_name='RMSE')),
                ('mae', models.FloatField(blank=True, null=True, verbose_name='MAE')),
                ('mape', models.FloatField(blank=True, null=True, verbose_name='MAPE (%)')),
                ('roc_auc', models.FloatField(blank=True, null=True, verbose_name='ROC-AUC')),
                ('last_trained', models.DateTimeField(blank=True, null=True, verbose_name='Dernier entraînement')),
                ('training_frequency', models.CharField(choices=[('manual', '👤 Manuel'), ('hourly', '🕓 Horaire'), ('daily', '📅 Quotidien'), ('weekly', '📆 Hebdomadaire'), ('monthly', '🗓️ Mensuel')], default='manual', max_length=20, verbose_name="Fréquence d'entraînement")),
                ('training_duration_ms', models.FloatField(blank=True, null=True, verbose_name="Durée d'entraînement (ms)")),
                ('training_data_size', models.PositiveIntegerField(blank=True, null=True, verbose_name="Taille des données d'entraînement")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('tags', models.JSONField(blank=True, default=list, validators=[apps.ml_analytics.validators.validate_tags], verbose_name='Tags')),
                ('model_file', models.FileField(blank=True, upload_to='ml_models/%Y/%m/', verbose_name='Fichier modèle')),
                ('scaler_file', models.FileField(blank=True, upload_to='ml_models/%Y/%m/', verbose_name='Fichier scaler')),
                ('dimensional_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='star_schema.dimensionalschema', verbose_name='Schéma dimensionnel')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_models', to='data_warehouse.measure', verbose_name='Mesure cible')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_models', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_models', to='users.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Modèle ML',
                'verbose_name_plural': 'Modèles ML',
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('forecast_period', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('year', 'Année')], default='month', max_length=20, verbose_name='Période')),
                ('horizon', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Horizon (nb de périodes)')),
                ('confidence_level', models.PositiveIntegerField(choices=[(80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (99, '99%')], default=95, verbose_name='Niveau de confiance (%)')),
                ('data', models.JSONField(blank=True, default=list, verbose_name='Données prévues')),
                ('lower_bounds', models.JSONField(blank=True, default=list, verbose_name='Bornes inférieures')),
                ('upper_bounds', models.JSONField(blank=True, default=list, verbose_name='Bornes supérieures')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Précision')),
                ('mape', models.FloatField(blank=True, null=True, verbose_name='MAPE (%)')),
                ('forecast_date', models.DateTimeField(verbose_name='Date de prévision')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Utilisée')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_forecasts', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='ml_analytics.mlmodel')),
            ],
            options={
                'verbose_name': 'Prévision',
                'verbose_name_plural': 'Prévisions',
                'db_table': 'forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Détecté le')),
                ('date', models.DateField(db_index=True, verbose_name="Date de l'anomalie")),
                ('value', models.FloatField(verbose_name='Valeur réelle')),
                ('expected_value', models.FloatField(verbose_name='Valeur attendue')),
                ('deviation', models.FloatField(verbose_name='Écart absolu')),
                ('deviation_percentage', models.FloatField(verbose_name='Écart (%)')),
                ('severity', models.CharField(choices=[('low', '🟢 Faible'), ('medium', '🟡 Moyenne'), ('high', '🟠 Haute'), ('critical', '🔴 Critique')], db_index=True, default='medium', max_length=20, verbose_name='Sévérité')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmée')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Résolue')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('dimensional_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='star_schema.dimensionalschema')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='data_warehouse.measure')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ml_analytics.mlmodel')),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Démarré'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], db_index=True, max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Précision')),
                ('loss', models.FloatField(blank=True, null=True, verbose_name='Perte')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='Durée (ms)')),
                ('data_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille des données')),
                ('batch_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille de lot')),
                ('epochs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Époques')),
                ('started_at', models.DateTimeField(verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='ml_analytics.mlmodel')),
            ],
            options={
                'verbose_name': "Journal d'entraînement",
                'verbose_name_plural': "Journaux d'entraînement",
                'db_table': 'model_training_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('dashboard', '📊 Tableau de bord'), ('kpi', '📈 KPI'), ('report', '📄 Rapport'), ('insight', '💡 Insight'), ('action', '⚡ Action')], db_index=True, max_length=20, verbose_name='Type')),
                ('target_id', models.UUIDField(verbose_name='ID de la cible')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confiance (%)')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=20, verbose_name='Priorité')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score brut')),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='Appliquée')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Appliquée le')),
                ('is_dismissed', models.BooleanField(db_index=True, default=False, verbose_name='Ignorée')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ignorée le')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_recommendations', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ml_analytics.mlmodel')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'db_table': 'recommendations',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=200, verbose_name='Nom du segment')),
                ('segment_description', models.TextField(blank=True, verbose_name='Description')),
                ('segment_id', models.PositiveIntegerField(verbose_name='ID du segment')),
                ('size', models.PositiveIntegerField(default=0, verbose_name="Nombre d'éléments")),
                ('percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage (%)')),
                ('characteristics', models.JSONField(default=dict, verbose_name='Caractéristiques')),
                ('avg_value', models.FloatField(blank=True, null=True, verbose_name='Valeur moyenne')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valeur min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valeur max')),
                ('sum_value', models.FloatField(blank=True, null=True, verbose_name='Somme')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='ml_analytics.mlmodel')),
            ],
            options={
                'verbose_name': 'Résultat de segmentation',
                'verbose_name_plural': 'Résultats de segmentation',
                'db_table': 'segmentation_results',
                'ordering': ['-percentage'],
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['name'], name='ml_models_name_10aec2_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', 'status'], name='ml_models_model_t_426c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['dimensional_schema'], name='ml_models_dimensi_6a2552_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['owner', 'team'], name='ml_models_owner_i_77637d_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['-last_trained'], name='ml_models_last_tr_771a51_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['is_active', 'status'], name='ml_models_is_acti_566692_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['model', '-forecast_date'], name='forecasts_model_i_3d3544_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['forecast_period'], name='forecasts_forecas_8dcec5_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['is_used'], name='forecasts_is_used_e0fa90_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['model', '-detected_at'], name='anomalies_model_i_4f946b_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['severity'], name='anomalies_severit_58cc06_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['date'], name='anomalies_date_fca962_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['is_confirmed', 'is_resolved'], name='anomalies_is_conf_51bcda_idx'),
        ),
        migrations.AddIndex(
            model_name='modeltraininglog',
            index=models.Index(fields=['model', '-started_at'], name='model_train_model_i_f5f27b_idx'),
        ),
        migrations.AddIndex(
            model_name='modeltraininglog',
            index=models.Index(fields=['status'], name='model_train_status_17c888_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['model', 'recommendation_type'], name='recommendat_model_i_99e7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['-confidence'], name='recommendat_confide_71ee6a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_applied', 'is_dismissed'], name='recommendat_is_appl_296581_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentationresult',
            index=models.Index(fields=['model', 'segment_id'], name='segmentatio_model_i_8b12a6_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentationresult',
            index=models.Index(fields=['-percentage'], name='segmentatio_percent_6c69d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentationresult',
            unique_together={('model', 'segment_id')},
        ),
    ]
