# Generated by Django 6.0.3 on 2026-03-21 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('core', '🔧 Core'), ('users', '👥 Utilisateurs'), ('data_sources', '🗄️ Sources de données'), ('etl', '🔄 ETL'), ('warehouse', '🏢 Entrepôt'), ('visualizations', '📊 Visualisations'), ('dashboards', '📈 Tableaux de bord'), ('kpis', '🎯 KPIs'), ('reports', '📑 Rapports'), ('notifications', '🔔 Notifications'), ('admin', '⚙️ Administration')], max_length=50, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.JSONField(default=list, help_text='Liste des codes de permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('superadmin', '👑 Super Administrateur BI'), ('admin', '⚙️ Administrateur BI'), ('bi_analyst', '📊 Analyste BI'), ('bi_developer', '💻 Développeur BI'), ('bi_consumer', '📱 Consommateur BI'), ('viewer', '👀 Observateur')], db_index=True, default='bi_consumer', max_length=30)),
                ('status', models.CharField(choices=[('active', '✅ Actif'), ('inactive', '⏸️ Inactif'), ('suspended', '🚫 Suspendu'), ('locked', '🔒 Verrouillé')], default='active', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Tentatives échouées')),
                ('account_locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Compte verrouillé jusqu'au")),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP')),
                ('api_access_enabled', models.BooleanField(default=True, verbose_name='Accès API')),
                ('api_rate_limit', models.IntegerField(default=1000, help_text='Requêtes par heure', verbose_name='Limite API')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Fuseau horaire')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=20, verbose_name='Thème')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
                ('team_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name="Chef d'équipe")),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', '🔑 Connexion'), ('logout', '🚪 Déconnexion'), ('create', '➕ Création'), ('update', '📝 Modification'), ('delete', '🗑️ Suppression'), ('view', '👀 Visualisation'), ('export', '📤 Export'), ('import', '📥 Import'), ('share', '🔗 Partage'), ('schedule', '📅 Planification'), ('dashboard_create', '📊 Création dashboard'), ('dashboard_share', '🔗 Partage dashboard'), ('data_source_test', '🔌 Test source données'), ('etl_run', '🔄 Exécution ETL')], max_length=30, verbose_name='Action')),
                ('severity', models.CharField(choices=[('low', '🟢 Faible'), ('medium', '🟡 Moyenne'), ('high', '🟠 Élevée'), ('critical', '🔴 Critique')], default='low', max_length=20, verbose_name='Sévérité')),
                ('description', models.TextField(verbose_name='Description')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='Type de ressource')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID ressource')),
                ('resource_name', models.CharField(blank=True, max_length=200, verbose_name='Nom ressource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(default=dict, verbose_name='Métadonnées')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-created_at'], name='user_activi_user_id_47a698_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action'], name='user_activi_action_b4118c_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['severity'], name='user_activi_severit_f84712_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['resource_type', 'resource_id'], name='user_activi_resourc_b3d2c3_idx'),
        ),
    ]
