# Generated by Django 6.0.3 on 2026-05-16 05:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_datasourcefile_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='file_type',
            field=models.CharField(blank=True, choices=[('csv', '📊 CSV'), ('xlsx', '📈 Excel (XLSX)'), ('yaml', '📋 YAML'), ('json', '🔧 JSON'), ('tsv', '📑 TSV (Tabulé)'), ('html', '🌐 HTML')], max_length=20, null=True, verbose_name='Type de fichier'),
        ),
        migrations.AlterField(
            model_name='datasourcefile',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='data_sources.datasource'),
        ),
        migrations.AlterField(
            model_name='datasourcefile',
            name='file',
            field=models.FileField(upload_to='data_sources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls', 'yaml', 'yml', 'json', 'tsv', 'html', 'htm'])], verbose_name='Fichier'),
        ),
    ]
